# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  meca_axis_1_joint:
    has_position_limits: true
    min_position: -3.05433
    max_position: 3.05433
    has_velocity_limits: true
    max_velocity: 2.61799
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0

  meca_axis_2_joint:
    has_position_limits: true
    min_position: -1.22173
    max_position: 1.5708
    has_velocity_limits: true
    max_velocity: 2.61799
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0

  meca_axis_3_joint:
    has_position_limits: true
    min_position: -2.35619
    max_position: 1.22173
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0

  meca_axis_4_joint:
    has_position_limits: true
    min_position: -2.96706
    max_position: 2.96706
    has_velocity_limits: true
    max_velocity: 5.23599
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0

  meca_axis_5_joint:
    has_position_limits: true
    min_position: -2.00713
    max_position: 2.00713
    has_velocity_limits: true
    max_velocity: 5.23599
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0

  meca_axis_6_joint:
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    max_velocity: 8.72665
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 10.0
