meca_arm_group:
    kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    kinematics_solver_timeout: 0.1
    kinematics_solver_attempts: 5
    kinematics_solver_search_resolution: 0.005
    position_only_ik: false
