meca_arm_group:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin   # oder KDL / IKFast
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  # TRAC-IK-spezifisch:
  solve_type: Distance   # Speed | Distance | Manipulation1 | Manipulation2
  position_only_ik: false
