# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager

moveit_simple_controller_manager:
  controller_names:
    - meca_arm_group_controller

  meca_arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
