# mecademic_moveit_config/config/ros2_controllers.yaml

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    meca_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

meca_arm_group_controller:
  ros__parameters:
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_nonzero_velocity_at_trajectory_end: true
