moveit_servo:
  ros__parameters:

    ## ----------- WICHTIG – sonst KEINE Eingabe möglich ----------- ##
    command_type: joint            # joint | twist -> DEIN FALL: joint jog
    command_in_type: speed_units   # damit echte Geschwindigkeiten gehen
    ## ------------------------------------------------------------- ##

    move_group_name: meca_arm_group
    planning_frame: world

    ## Eingangs-Topics (joint / twist)
    joint_command_in_topic: /moveit_servo/delta_joint_cmds
    cartesian_command_in_topic: /moveit_servo/delta_twist_cmds
    joint_topic: /joint_states

    ## Ausgang an Controller
    command_out_topic: /meca_arm_group_controller/joint_trajectory
    command_out_type: trajectory_msgs/JointTrajectory

    ## Ausgabe-Timing
    publish_period: 0.01
    publish_joint_positions: true
    publish_joint_velocities: false
    publish_joint_accelerations: false

    ## Skalierung
    scale:
      linear: 0.2
      rotational: 0.8
      joint: 0.5

    incoming_command_timeout: 0.2
    override_velocity_scaling_factor: 1.0
    check_collisions: false
    apply_twist_commands_about_ee_frame: true

    ## Singularitäten
    lower_singularity_threshold: 30.0
    hard_stop_singularity_threshold: 45.0

    ## Smoothing deaktiviert
    use_smoothing: false
