home:
  frame: "world"
  xyz: [0.5, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 0.0]

predispense:
  frame: "world"
  xyz: [0.2, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 0.0]

service:
  frame: "world"
  xyz: [-0.5, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 0.0]
