version: 1
profiles:
  default:
    history: KEEP_LAST
    depth: 10
    reliability: RELIABLE
    durability: VOLATILE

  latched:
    history: KEEP_LAST
    depth: 1
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL

  sensor_data:
    history: KEEP_LAST
    depth: 5
    reliability: BEST_EFFORT
    durability: VOLATILE

  # optional:
  # deadline_ms: 0
  # lifespan_ms: 0
  # liveliness: SYSTEM_DEFAULT     # SYSTEM_DEFAULT | AUTOMATIC | MANUAL_BY_TOPIC
  # liveliness_lease_ms: 0
  # avoid_ros_namespace_conventions: false
