scene_objects:
  - id: cage
    mesh: "../resource/environment/cage_closed_0_5m.stl"
    frame: "world"
    position: [0.0, 0.25, 0.0]
    rpy_deg: [0.0, 0.0, 0.0]
    mesh_offset: [0.0, 0.0, 0.0]   # Verschiebung relativ zum TF-Frame
    mesh_rpy:    [0.0, 0.0, 0.0]   # Rotation vom Mesh (lokal)

  - id: substrate_mount
    mesh: "../resource/substrate_mounts/substrate_mount_flat_240x240x50.stl"
    frame: "world"
    position: [0.0, 0.25, 0.0]
    rpy_deg: [0.0, 0.0, 0.0]
    mesh_offset: [0.0, 0.0, 0.0]
    mesh_rpy:    [0.0, 0.0, 0.0]

  - id: scene
    mesh: ""
    frame: "substrate_mount"
    position: [0.0, 0.0, 0.05]
    rpy_deg: [0.0, 0.0, 0.0]
    mesh_offset: [0.0, 0.0, 0.0]
    mesh_rpy:    [0.0, 0.0, 0.0]

  - id: substrate
    mesh: "../resource/substrates/wafer_d200_h2.stl"
    optional: true
    frame: "scene"
    position: [0.0, 0.0, 0.0]
    rpy_deg: [0.0, 0.0, 0.0]
    mesh_offset: [0.0, 0.0, 0.0]   # z.B. später Höhe anpassen?
    mesh_rpy:    [0.0, 0.0, 0.0]
