version: 1
active_mount: "flat_240x240"

mounts:
  flat_240x240:
    description: "Standard Flachhalter 240x240mm"
    mesh: "package://mecademic_bringup/resource/substrate_mounts/substrate_mount_flat_240x240x50.stl"
    scene_offset:
      xyz: [0.0, 0.0, 50.0]   # scene liegt 50 mm über der Mount-Oberfläche
      rpy_deg: [0.0, 0.0, 0.0]

  circle_d240:
    description: "Rundhalter Ø240mm"
    mesh: "package://mecademic_bringup/resource/substrate_mounts/substrate_mount_circle_d240_h50.stl"
    scene_offset:
      xyz: [0.0, 0.0, 50.0]
      rpy_deg: [0.0, 0.0, 0.0]

  post_d30_h100:
    description: "Post-Holder Ø30 × H100"
    mesh: "package://mecademic_bringup/resource/substrate_mounts/substrate_mount_post_d30mm_h100mm.stl"
    scene_offset:
      xyz: [0.0, 0.0, 100.0]
      rpy_deg: [0.0, 0.0, 0.0]
