active_tool: "spray_nozzle_01"

tools:
  no_tool:
    description: "Kein Tool aktiv"
    plugin: "no_tool"
    mount_frame: "tool_mount"
    tcp_offset: [0.0, 0.0, 0.0]
    tcp_rpy:    [90.0, 0.0, -90.0]
    mesh: ""
    mesh_offset: [0.0, 0.0, 0.0]
    mesh_rpy:    [0.0, 0.0, 0.0]

  spray_nozzle_01:
    description: "Spray Nozzle 01"
    plugin: "spray_nozzle_01"
    mount_frame: "tool_mount"
    tcp_offset: [0.086, 0.02, 0.04]
    tcp_rpy:    [90.0, 0.0, -90.0]
    mesh: "package://mecademic_bringup/resource/tools/spray_nozzle_01.stl"
    mesh_offset: [0.001, 0.0, 0.0]
    mesh_rpy:    [0.0, 90.0, 0.0]

  spray_nozzle_02:
    description: "Spray Nozzle 02"
    plugin: "spray_nozzle_02"
    mount_frame: "tool_mount"
    tcp_offset: [0.05, 0.0, 0.05]
    tcp_rpy:    [0.0, -90.0, 0.0]
    mesh: "package://mecademic_bringup/resource/tools/spray_nozzle_01.stl"
    mesh_offset: [0.0, 0.0, 0.0]
    mesh_rpy:    [0.0, 90.0, 0.0]
