active_tool: "spray_nozzle_01"

tools:
  none:
    description: "Kein Tool aktiv"
    mount_frame: "tool_mount"
    tcp_offset: [0.0, 0.0, 0.0]
    tcp_rpy:    [0.0, 0.0, 0.0]
    mesh: ""           # kein Mesh

  spray_nozzle_01:
    description: "Spray Nozzle 01"
    mount_frame: "tool_mount"
    tcp_offset: [0.0, 0.0, 0.120]   # Beispiel
    tcp_rpy:    [0.0, 0.0, 0.0]
    mesh: "package://mecademic_bringup/resource/tools/spray_nozzle_01.stl"

  spray_nozzle_02:
    description: "Spray Nozzle 02"
    mount_frame: "tool_mount"
    tcp_offset: [0.0, 0.0, 0.135]
    tcp_rpy:    [0.0, 0.0, 0.0]
    mesh: "package://mecademic_bringup/resource/tools/spray_nozzle_02.stl"
