version: 1

topics:
  servo:
    subscribe:
      - id: cartesian_mm
        name: /servo/cartesian_mm
        type: geometry_msgs/msg/TwistStamped
        qos: sensor_data        # BEST_EFFORT (CLI: --qos-reliability best_effort)
      - id: joint_jog
        name: /servo/joint_jog
        type: control_msgs/msg/JointJog
        qos: sensor_data
      - id: set_mode
        name: /servo/set_mode
        type: std_msgs/msg/String
        qos: default            # RELIABLE
      - id: set_frame
        name: /servo/set_frame
        type: std_msgs/msg/String
        qos: default

    publish:
      - id: twist_out
        name: /servo/delta_twist_cmds
        type: geometry_msgs/msg/TwistStamped
        qos: sensor_data        # ← i.d.R. BEST_EFFORT wie MoveIt-Subscriber
      - id: joint_out
        name: /servo/delta_joint_cmds
        type: control_msgs/msg/JointJog
        qos: sensor_data

  tool:
    subscribe:
      - id: tool_select
        name: /meca/tool/select
        type: std_msgs/msg/String
        qos: default
      - id: tool_tcp_set
        name: /meca/tool/tcp/set
        type: geometry_msgs/msg/PoseStamped
        qos: default
    publish:
      - id: tool_state
        name: /meca/tool/state
        type: std_msgs/msg/String
        qos: latched
      - id: tool_tcp
        name: /meca/tool/tcp
        type: geometry_msgs/msg/PoseStamped
        qos: latched

  motion:
    subscribe:
      - id: plan_waypoints
        name: /meca/motion/plan/waypoints
        type: geometry_msgs/msg/PoseArray
        qos: default
      - id: plan_named
        name: /meca/motion/plan/named
        type: std_msgs/msg/String
        qos: default
      - id: execute
        name: /meca/motion/execute
        type: std_msgs/msg/Bool
        qos: default
      - id: stop
        name: /meca/motion/stop
        type: std_msgs/msg/Empty
        qos: default
    publish:
      - id: trajectory
        name: /meca/motion/trajectory
        type: trajectory_msgs/msg/JointTrajectory
        qos: default
      - id: preview_markers
        name: /meca/motion/preview/markers
        type: visualization_msgs/msg/MarkerArray
        qos: latched
      - id: motion_result
        name: /meca/motion/result
        type: std_msgs/msg/String
        qos: default

  poses:
    subscribe:
      - id: pose_set
        name: /meca/poses/set
        type: geometry_msgs/msg/PoseStamped
        qos: default
      - id: pose_delete
        name: /meca/poses/delete
        type: std_msgs/msg/String
        qos: default
      - id: pose_rename
        name: /meca/poses/rename
        type: diagnostic_msgs/msg/KeyValue
        qos: default
      - id: poses_save
        name: /meca/poses/save
        type: std_msgs/msg/Empty
        qos: default
    publish:
      - id: poses_list
        name: /meca/poses/list
        type: geometry_msgs/msg/PoseArray
        qos: latched
      - id: poses_named
        name: /meca/poses/named
        type: diagnostic_msgs/msg/KeyValue
        qos: latched
      - id: poses_changed
        name: /meca/poses/changed
        type: std_msgs/msg/String
        qos: default

  scene:
    subscribe:
      - id: scene_load
        name: /meca/scene/load
        type: std_msgs/msg/String
        qos: default
      - id: substrate_set_pose
        name: /meca/scene/substrate/set_pose
        type: geometry_msgs/msg/PoseStamped
        qos: default
    publish:
      - id: scene_markers
        name: /meca/scene/markers
        type: visualization_msgs/msg/MarkerArray
        qos: latched
      - id: scene_loaded
        name: /meca/scene/loaded
        type: std_msgs/msg/String
        qos: default

  status:
    publish:
      - id: heartbeat
        name: /meca/status/heartbeat
        type: std_msgs/msg/UInt32
        qos: default
      - id: diagnostics
        name: /meca/status/diagnostics
        type: diagnostic_msgs/msg/DiagnosticArray
        qos: default
