# Starte ROS2-Bringup automatisch (true) oder nicht (false).
launch: false

# Welt -> meca_mount
world_to_meca_mount:
  xyz: [0.0, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 90.0]

# Substrate-Mount (Workspace-Mount)
workspace_mount:
  enable: true
  mesh_path: resource/stl/substrate_mounts/substrate_mount_flat_240x240x50.stl
  xyz: [0.20, 0.00, 0.00]
  rpy_deg: [0.0, 0.0, 0.0]

# Umgebung / Käfig
cage:
  enable: true
  mesh_path: resource/stl/environment/cage.stl
  xyz: [0.0, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 0.0]
