version: 1
disable_existing_loggers: false

formatters:
  brief:
    format: "%(levelname).1s %(name)s: %(message)s"
  default:
    format: "%(asctime)s %(levelname)s [%(process)d] %(name)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  # Konsole
  console_info:
    class: logging.StreamHandler
    level: INFO
    formatter: brief
    stream: ext://sys.stdout

  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: default
    stream: ext://sys.stderr

  # Rotierende Files (1 MB, 5 Backups)
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/app.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  process_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/process.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  recipe_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/recipe.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  service_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/service.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  system_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/system.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  ros_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/ros.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8

  ros_launch_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "${LOG_DIR}/ros.launch.log"
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8
    
  stderr_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: default
    filename: "${LOG_DIR}/stderr.log"
    maxBytes: 1048576   # 1 MB
    backupCount: 5
    encoding: utf-8

loggers:
  # feingranulare Logger pro Tab / ROS
  app:
    level: DEBUG
    handlers: [app_file, console_info, console_err]
    propagate: false

  app.tabs.process:
    level: DEBUG
    handlers: [process_file, console_info, console_err]
    propagate: false

  app.tabs.recipe:
    level: DEBUG
    handlers: [recipe_file, console_info, console_err]
    propagate: false

  app.tabs.service:
    level: DEBUG
    handlers: [service_file, console_info, console_err]
    propagate: false

  app.tabs.system:
    level: DEBUG
    handlers: [system_file, console_info, console_err]
    propagate: false

  ros:
    level: DEBUG
    handlers: [ros_file, console_info, console_err]
    propagate: false

  ros.ros_launcher:
    level: DEBUG
    handlers: [ros_file, console_info, console_err]
    propagate: false

  ros.kill_all_ros:
    level: DEBUG
    handlers: [ros_file, console_info, console_err]
    propagate: false

  ros.launch:
    level: DEBUG
    handlers: [ros_launch_file, console_info, console_err]
    propagate: false

  stderr:
    level: ERROR
    handlers: [stderr_file, console_err]
    propagate: false


# Root kriegt nur die Konsole; Fach-Logger schreiben in ihre Files
root:
  level: INFO
  handlers: [console_info, console_err]
